spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.199.194:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
logging:
  pattern:
    console: "%d - %msg%n"
  level: debug
server:
  context-path: /sell
weChat:
#  微信授权
  mpAppId: wx2f0ca69f45b1075e
  mpAppSecret: fb863a5f7498fe9fb18ee5a3ae78c673

