spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.199.194:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://localhost:3306/weixin?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    password: debugjoker
  jpa:
    show-sql: true
logging:
  pattern:
    console: "%d - %msg%n"
  level: debug
server:
  context-path: /sell
