spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.2.250:3306/sell?useUnicode=true&characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
logging:
  pattern:
    console: "%d - %msg%n"
  level: debug
server:
  context-path: /sell
weChat:
  #  微信授权
  mpAppId: wx3bd6c78bb9b9d8fb
  mpAppSecret: 8f4b53d1c20d36cca8ab6907afe74abe
  #  商户密钥及商户id
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  #  微信退款证书路径
  keyPath: /var/weixin_cert/h5.p12
  #  微信通知调用方法
  notifyUrl: http://zlq.xxgblog.com/sell/pay/notify

projectUrl:
  wechatMpAuthorize: http://zlq.xxgblog.com
  sell: http://zlq.xxgblog.com

